### ISSUE TITLE
Git tags for releases/versions...

### ISSUE THREAD

**Issue by ido** [exablaze-oss/exanic-software#4]
Please add git tags for each release/version to make it easier to debug, diff, and package this software.

Also, can you confirm that the current master is 2.0.1 and are there any differences between what's in this repository and the tarball in the RPM/DEB?

Thank you!

**Comment by eigenmatt** [comment]
Thanks Ido, that's a good idea, I've retrospectively added git tags for all the releases in the tree.

I can confirm that the current master is exactly 2.0.1.  The only difference between the repository and tarball is that the repository has an internal version number suffixed with -git (occasionally we do push important fixes to github in advance of a release so this helps identify that binaries were built from github sources).  In the future we may improve this to stamp the version number as part of the build process so that the dirty state can be tagged more intelligently.

Thank you also for building the Arch Linux packages.

Cheers, Matt

**Comment by ido** [comment]
Excellent!  Thanks for the quick work.
